service: sounds-of-middle-earth-lambda

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1
  memorySize: 128
  # vpc:
  #   securityGroupIds:
  #     - securityGroupId1
  #     - securityGroupId2
  #   subnetIds:
  #     - subnet-1
  #     - subnet-2

functions:
  getApiInfo:
    description: Returns information about the API itself
    name: some-v1-get-api-info
    handler: src/handlers/App.getApiInfo
    memorySize: 512
    timeout: 5
    reservedConcurrency: 2
    events:
      - http:
          path: /api/v1/info
          method: GET
          cors: true

  getLotrQuote:
    description: Returns a random quote from the Lord of the Rings series
    name: some-v1-get-lotr-quote
    handler: src/handlers/LOTR.getLOTRQuote
    memorySize: 512
    timeout: 5
    reservedConcurrency: 2
    environment:
      LOTR_API_TOKEN: ${env:LOTR_API_TOKEN}
    events:
      - http:
          path: /api/v1/lotr/quote
          method: GET
          cors: true
