service: sounds-of-middle-earth-lambda

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1
  memorySize: 128


functions:
  getApiInfo:
    name: some-v1-get-api-info
    handler: src/handlers/App.getApiInfo
    reservedConcurrency: 1
    events:
      - http:
          path: /api/v1/info
          method: GET
          cors: true

  getLotrQuote:
    name: some-v1-get-lotr-quote
    handler: src/handlers/LOTR.getLOTRQuote
    environment:
      LOTR_API_TOKEN: ${env:LOTR_API_TOKEN}
    events:
      - http:
          path: /api/v1/lotr/quote
          method: GET
          cors: true
