# # # # # # # # # # #
#       SETUP       #
# # # # # # # # # # #
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1.0
  serverless-framework: circleci/serverless-framework@2.0
  node: circleci/node@5.0.2
# # # # # # # # # # #
#       JOBS        #
# # # # # # # # # # #
jobs:
  # # # # # # # # # # #
  #      BACKEND      #
  # # # # # # # # # # #
  deploy-backend:
      executor: serverless-framework/default
      steps:
        - checkout:
            path: ~/sounds-of-middle-earth
        - attach_workspace:
            at: ~/sounds-of-middle-earth/backend
        - aws-cli/setup
        - serverless-framework/setup
        - run:
            name: list files
            command: ls
        - run:
            name: deploy-backend
            command: sls deploy -v
  # # # # # # # # # # #
  #      FRONTEND     #
  # # # # # # # # # # #
  build-frontend:
    docker:
      - image: circleci/node:latest
    working_directory: ~/sounds-of-middle-earth/frontend
    steps:
      - checkout:
          path: ~/sounds-of-middle-earth
      - attach_workspace:
          at: ~/sounds-of-middle-earth/frontend
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - node/install-packages:
          cache-path: ~/sounds-of-middle-earth/frontend/node_modules
          override-ci-command: npm install --production=false
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: ls -l node_modules/vite
          command: ls -l node_modules
      - run:
          name: Build project
          command: npm run build;
      - persist_to_workspace:
          root: .
          paths:
            - dist
  deploy-frontend:
    docker:
      - image: circleci/golang:1.17.3
    working_directory: ~/sounds-of-middle-earth/frontend
    steps:
    - checkout:
        path: ~/sounds-of-middle-earth
    - attach_workspace:
        at: ~/sounds-of-middle-earth/frontend
    - restore_cache:
        key: v1-pkg-cache
    - run:  go get -v github.com/bep/s3deploy/v2
    - save_cache:
        key: v1-pkg-cache
        paths:
           - /go/pkg
    - run:
        name: Deploy to S3
        command: |
          s3deploy -source=dist/ -region=eu-west-1 -key=$AWS_ACCESS_KEY_ID -secret=$AWS_SECRET_ACCESS_KEY -distribution-id=$AWS_CLOUDFRONT_DISTRIBUTION_ID -bucket=$BUCKET_NAME

# # # # # # # # # # #
#      WORKFLOWS    #
# # # # # # # # # # #
workflows:
  version: 2
  build-and-deploy-frontend:
    jobs:
      - build-frontend:
          filters:
            branches:
              only:
              - master
      - deploy-frontend:
          requires:
            - build-frontend
          filters:
            branches:
              only:
              - master
  build-and-deploy-backend:
    jobs:
      - deploy-backend:
          filters:
            branches:
              only:
              - master